  Default branch is: master
  🚀 Creating new Codespace (4h idle timeout)...
    ✓ Codespaces usage for this repository is paid for by songyoungchi
  ✅ Codespace created: shiny-happiness-gxqv55jw7774fv56j
  ⏳ Waiting for Xray to start (180s)...
  jq: parse error: Expected string key before ':' at line 1, column 4
  Error: Process completed with exit code 5.
  ##[debug]Set output cs_name = shiny-happiness-gxqv55jw7774fv56j
  ##[debug]Finishing: Create codespace and get VLESS link
